name: Frinx Services Python Workers feature request
description: Suggest a new feature
labels: [feature request]

body:
  - type: markdown
    attributes:
      value:  Thank you for contributing to frinx-services-python-workers!

  - type: checkboxes
    id: searched
    attributes:
      label: Initial Checks
      description: |
        Just a few checks to make sure you need to create a feature request.

      options:
        - label: I have searched for similar requests and couldn't find anything
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please give as much detail as possible about the feature you would like to suggest.

        You might like to add:
        * A demo of how code might look when using the feature
        * Your use case(s) for the feature
        * Why the feature should be added to frinx-services-python-workers
    validations:
      required: true
